### ISSUE TITLE
[cfp] Privacy and mapping

### ISSUE THREAD

**Issue by wseltzer** [Maps4HTML/Maps4HTML-Workshop-2020#10]
Locational privacy (both of people's physical location and of the locations they investigate) is a hot topic. See e.g. [NYT](https://www.nytimes.com/interactive/2019/12/19/opinion/location-tracking-cell-phone.html)

Please acknowledge that subject, and make explicit how much of it you want this workshop to cover. Are you open to covering privacy-preserving techniques for viewing, such as client-side search and rendering, multiple-fetching, or are those out-of-scope? Mitigating fingerprinting risks and considering the privacy threat model of APIs discussed should be in-scope.

**Comment by prushforth** [comment]
> Locational privacy (both of people's physical location and of the locations they investigate) is a hot topic.

We are open to discussing these topics.  I will include a bullet in the suggested topics list.  Can you suggest the bullet or two that bring out the topics you would like to see up for discussion?

**Comment by AmeliaBR** [comment]
Closing based on Wendy's “review completed” tag here: https://github.com/w3c/strategy/issues/210

Reopen or add a new issue if any other specific concerns arise.
