### ISSUE TITLE
[cfp] Security

### ISSUE THREAD

**Issue by wseltzer** [Maps4HTML/Maps4HTML-Workshop-2020#11]
You mention "security of browser-based maps" -- the topic bears expansion. For example, do you mean:
* security of web map applications and map mash-ups, with best practices for secure cross-site interaction? 
* map security against location-spoofing or misrepresentation?
* security of personal/business data of those on the map? 
* security of proprietary or confidential map overlays? 
* security of user interactions with the map? (confidentiality, integrity, authentication)

Are some security topics explicitly out-of-scope because better addressed elsewhere?

**Comment by AmeliaBR** [comment]
Thanks for this and #10, Wendy. I'm in the midst of a re-write of the CFP, but these points are very helpful in trying to elucidate what it should cover!

**Comment by AmeliaBR** [comment]
Closing based on Wendy's “review completed” tag here: https://github.com/w3c/strategy/issues/210

Reopen or add a new issue if any other specific concerns arise.
