### ISSUE TITLE
[cfp] Internationalization

### ISSUE THREAD

**Issue by xfq** [Maps4HTML/Maps4HTML-Workshop-2020#12]
Internationalization can be a workshop topic as well. For example, there should be ways to indicate/change the language and text direction of a map, and alters the map's behavior based on a given country or territory (e.g., address formats, different views of borders and so on).

**Comment by prushforth** [comment]
Good idea, we'll add that to the topics of interest. This also suggests another dimension of directed solicitations of interest to individuals from the il8n community.

**Comment by AmeliaBR** [comment]
I added (in #13)  a general point about internationalization to the [suggested topics list](https://maps4html.github.io/Maps4HTML-Workshop-2020/#topics).

I grouped it with accessibility issues because it seemed related to “different ways of interacting with a map”. But I'd be open to expanding on that if you think it would be helpful.

**Comment by r12a** [comment]
Note that i18n concerns may also require that map data is designed to store the differences. For example: Names for the same place, river, sea, etc are certainly different from country/language to language, which indicates that the map data must be capable of storing those alternatives, as well as capable of allowing the user to express the linguistic/regional point of view from which they want to interact with the map.  It will also need to store bidirectional script metadata for proper display of many languages.

Country boundary expectations may also differ from country to country.  I suspect that names for regions on a map may involve differences in the size and extent of the area named, as well as the name change.

I wonder whether different populations will have different expectations about features of interest on a map(?). Or whether the need to change names is accompanied by the need to use different map symbols, line styles, etc.

**Comment by AmeliaBR** [comment]
Just pushed an edit integrating @r12a's suggestions. The [potential topics](https://maps4html.org/Maps4HTML-Workshop-2020/#topics) list now includes:

- Creating truly global Web map experiences that work with different languages and cartographic practices; including
  * linguistic and cultural considerations when internationalizing map-viewer interaction patterns
  * integrating translations of place names in map data, and allowing users to select preferred language
  * adapting iconography or other visual cues to local conventions
  * working with politically disputed geographic names and boundaries

Let us know if you have any remaining concerns; we hope to go live / promote the website on Monday.

**Comment by prushforth** [comment]
Some of these are advanced cartography concepts that are of concern the map maker for certain. I wonder if we've come across how these are handled by existing commercial Web mapping service providers in our review of [requirements for Web maps](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/)?  

As far as politically disputed names and boundaries goes, I'm not sure there can be a technical solution.  Maps are a form of human expression, like prose or graphics, and such things can't really be controlled by a technical standard.  I'm not against them being on the list of ideas for discussion, but it will be interesting to see if someone puts forward a position about how such concepts could be incorporated into a standard; I would like to read that paper!

**Comment by AmeliaBR** [comment]
> As far as politically disputed names and boundaries goes, I'm not sure there can be a technical solution.

The solution is more about making sure the map service can easily substitute part of the data as required based on the user's locale. Now, that might turn out to be a strictly server-side solution & not appropriate for a front-end web standard, but still, worth acknowledging as a difficult reality for map makers.

**Comment by AmeliaBR** [comment]
@r12a, @xfq We're building the agenda right now. Didn't get as many submissions on the internationalization topic as we'd like. We have one talk proposal about text layout issues in CJK, but we were hoping to compliment that with a panel discussion. Do you have any suggestions of who to ask to participate? Or would you be willing to do so yourself?

The info for contacting the programming committee is at https://www.w3.org/2020/maps/call-for-participation#program-committee

**Comment by r12a** [comment]
@AmeliaBR (sorry for the delay). No names spring to mind, since i don't really have contacts in the mapping world. Sorry about that.  I'll certainly point people your way if i find someone.

**Comment by xfq** [comment]
Sorry, I don't have contacts on the internationalization topic of mapping either. I know W3C members who may be interested in this topic (a native map viewer for the web platform), tho, and I will invite them to attend the workshop.
