### ISSUE TITLE
Add missing captions file

### ISSUE THREAD

**Issue by nchan0154** [Maps4HTML/Maps4HTML-Workshop-2020#133]
Captions (.vtt file) are missing for [Week 2 Day 1/September 28](https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/tree/master/supporting-material-uploads/minutes)

The other captions have been copy-edited and can be reuplaoded to Youtube.

**Comment by prushforth** [comment]
I believe it's actually week 2 day 1 that's missing (2020-09-28).  I hope so anyway because that's the one I added, so let me know if not!  Thank you! Edit: confusion!  However I think I uploaded the file you're looking for.

**Comment by nchan0154** [comment]
Yep that's it! I can edit these too, thanks!
