### ISSUE TITLE
Workshop Report Feedback

### ISSUE THREAD

**Issue by tguild** [Maps4HTML/Maps4HTML-Workshop-2020#138]
Please provide your feedback as a github issue or create a pull request no later than 23 December.

**Comment by Malvoz** [comment]
Edit: resolved in https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/pull/141/commits/4987945fc3ef97cc8c9f537515ebd98c85a4ec95.

I can't tell if some text is missing, or just a missing closing parenthesis somewhere after "(the Web Plat" (at [L16](https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/blame/master/supporting-material-uploads/report/report.md#L16)):

> The workshop demonstrated the receptiveness on the part of the Web standards community, to the idea of standardizing maps in browsers (the Web Plat, with the caveat that the work will be costly and time consuming. Web Platform advocates suggest that efforts to standardize maps should be incremental in nature, starting with use cases and requirements, and proceeding to specification and development. In the light of such willingness to cooperate, and with the knowledge that the Web Platform is the last and only “even playing field” in our global information space, it is imperative that the geospatial standards community continue, and to increase our participation in Web standards development, promulgating standard and simplified access to maps and spatial information (maps in HTML), for everyone, of all abilities.

**Comment by Malvoz** [comment]
The deadline for feedback has passed, should this be closed?
