### ISSUE TITLE
Program Committee members to add

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-Workshop-2020#14]
- [x] Roy Rathbun, NGA
- [x] Don Sullivan, NASA

**Comment by AmeliaBR** [comment]
Closed via 258ab727d26892be9dbd0f54f437a37ddab5ea21 (and subsequent typo fix)

**Comment by prushforth** [comment]
- [ ] Doug Schepers

**Comment by prushforth** [comment]
Please add Tom Kralidis, Environment and Climate Change Canada, Meteorological Service of Canada as a program committee member (@tomkralidis ).  Thanks, Tom!
