### ISSUE TITLE
Remove the 'Currently Seeking Sponsorship' panel

### ISSUE THREAD

**Issue by ghobona** [Maps4HTML/Maps4HTML-Workshop-2020#147]
Since the workshop has ended, please remove the 'Currently Seeking Sponsorship' panel.

![Screenshot 2021-02-02 at 15 42 49](https://user-images.githubusercontent.com/18121038/106624270-624d3600-656d-11eb-9d5c-c87fe84e1f71.png)

**Comment by prushforth** [comment]
Bumping this as the report will be published soon...

**Comment by AmeliaBR** [comment]
Closed via #150
