### ISSUE TITLE
Integrate new branding / logos / header image

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML-Workshop-2020#20]
I've got a package of graphics put together by Bennett Feely, need to add them to the repo and update the templates to use them.

**Comment by prushforth** [comment]
I added the NRCan wordmark graphic to the media assets.  I had a look to see if it looked ok on my desktop, but not on mobile.  Did not update the templates, I guess I'll leave that to you when pushing final updates, as we'll have another discussion about branding this week, I believe.

**Comment by prushforth** [comment]
I added the NRCan wordmark graphic to the media assets.  I had a look to see if it looked ok on my desktop, but not on mobile.  Did not update the templates, I guess I'll leave that to you when pushing final updates, as we'll have another discussion about branding this week, I believe.

**Comment by AmeliaBR** [comment]
Still to do:

- add favicons / home screen icons.
- Maybe figure out somewhere to host the higher res assets. (Although, the main purpose of having higher-res assets was to create posters & other in-person signage, which I guess isn't going to be necessary anymore.

**Comment by prushforth** [comment]
I like the community group favicon, and its message.😊
