### ISSUE TITLE
Hashtag & other social media

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML-Workshop-2020#21]
@ghobona suggested that we lock on a hashtag in advance so we can keep social media communication organized.

Current plan is use #maps4HTML, which matches the short name used for the Maps for HTML Community Group, and its [`@maps4HTML`](https://twitter.com/maps4html) twitter account.

The formal name for the workshop itself is slightly more general: Maps for the Web.

**Comment by prushforth** [comment]
I suggest [#Maps4HTML](https://twitter.com/hashtag/Maps4HTML?src=hashtag_click), although it is almost the same, I've been told that it helps the (situationally?) disabled to read the hashtag more readily.  YMMV.  I've used both before.

**Comment by AmeliaBR** [comment]
The #Maps4HTML hashtag is integrated into the header/logo of the website. We can mention it more explicitly in the Tools / Info for Participants section when that's filled out.
