### ISSUE TITLE
Suggested change: unit-less $ to $USD

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-Workshop-2020#22]
The sponsor page should probably list fees in USD, since W3C is a US company.  Thanks

**Comment by AmeliaBR** [comment]
A thanks, yes, this was brought up on a call but I forgot to follow up and make the change.

**Comment by prushforth** [comment]
Thanks! I would do it but it seems easier to leave edits to you and just put my 2¢ into issues.
