### ISSUE TITLE
Remote option

### ISSUE THREAD

**Issue by tguild** [Maps4HTML/Maps4HTML-Workshop-2020#31]
We should promote remote option up front and possibility the meeting may become remote only

https://www.w3.org/Guide/meetings/continuity

**Comment by AmeliaBR** [comment]
I've added some highlighted info blocks to the main page and the new Venue page, via https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/commit/096f42c2413f420f18fec0066c5b52ed0a6a9d7d

I'm open to additional suggestions about what to include.

**Comment by AmeliaBR** [comment]
I think this is now fully covered…
