### ISSUE TITLE
Make the "Supporting Material" section more related to important workshop background

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-Workshop-2020#33]
I suggest replacing the prose on the [page](https://maps4html.org/Maps4HTML-Workshop-2020/supporting-material) with something like the following, @ghobona can you agree to this:

> Background and Suggested Reading
>
> The Maps for HTML Community Group is a W3C community of individuals and organizations who share the objective of extending HTML with maps and location. The community group is “iterating” on a variety of outputs, ranging from [use cases and requirements]( https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/), to [proposals]( https://github.com/Maps4HTML/MapML-Proposal#the-mapml-proposal---explainermd), [polyfills]( https://geogratis.gc.ca/mapml/en/cbmtile/cbmt/) and [specifications]( https://maps4html.github.io/MapML/spec/).
>
> The motivation behind the Maps for HTML Community Group is the growing recognition of the importance of maps and location in decision-making at all levels, from individuals to humanity on a global scale. We see evidence of this in the growth of world-wide contributions to projects such as Open Street Map, as well as in the public investments by governments in open spatial data infrastructures. A negative aspect of this growth is the proliferation of incompatible APIs for creating and using maps and location.
>
> A key challenge in introducing a new standard for maps on the Web is to avoid creating a [more complex and “siloed” environment for users]( https://www.explainxkcd.com/wiki/index.php/927:_Standards), while respecting [the requirement of accessing existing content]( https://www.w3.org/DesignIssues/Principles.html#TOII).  As such, the fundamental proposition of this workshop is to discuss the costs, benefits and means of [extending HTML]( https://www.w3.org/TR/html-design-principles/#pave-the-cowpaths) to include maps and location information in a [developer-](https://extensiblewebmanifesto.org/) and user-oriented fashion.

**Comment by ghobona** [comment]
Agreed.

**Comment by AmeliaBR** [comment]
Thanks again for this text, Peter & thanks Gobe for turning it into a PR. And apologies it's taken me this long to review…

The first two paragraphs are great as an “About the Maps for HTML community group”. Maybe we should move it down to a subsection, so that it becomes an example of a background statement for a particular organization?

However, I don't want to put new text about the purpose of the workshop on this page, that would conflict with what is stated on the main page. 

And I don't think we need to throw out the text Gobe had previously written about OGC spec work. It just needs to be correctly framed.

I'll try to re-arrange things & push it back to the PR for you both to look at.

**Comment by AmeliaBR** [comment]
Update:

After playing around with both sections & cleaning up the rest of the page, I ended up dropping most of the text & just keeping links!

Both write-ups were very opinionated, which would be good for a position statement from an individual participant, but didn't seem a good fit for a list of background reading from the organizing committee.

Of course, it would be great if you wanted to be the first to submit an individual participant position statement, @prushforth! Or @ghobona, if you can get an official statement from OGC.

And finally, GitHub wouldn't let me amend the PR, so I've closed #41 & pushed my changes separately.

**Comment by AmeliaBR** [comment]
@prushforth, Any critiques on [the changes](https://maps4html.org/Maps4HTML-Workshop-2020/supporting-material), or can we close this issue?

**Comment by prushforth** [comment]
LGTM
