### ISSUE TITLE
Workshop postponed

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-Workshop-2020#36]
The workshop conveners agreed today that we should postpone the event until the coronavirus situation has resolved and people and organizations are free to plan travel etc.  

Please update the web site with a notice that a new date and location will be determined and announced.  We'll meet on Thursday to discuss what other information to convey at this time, but it was suggested that there is some urgency to update the web site quickly to reflect this decision.

Thanks

**Comment by AmeliaBR** [comment]
Added the following note, based on Peter's suggested wording:

> Due to risks associated with global travel and the potential spread COVID-19, the organizers of the Maps for the Web workshop have decided to **indefinitely postpone the workshop**, until we can be more confident of the health and safety of workshop participants.
> 
> We are currently reviewing all options, including rescheduling for a later date or organizing an online-only workshop.

@prushforth, can you send a note to the Maps for HTML CG mailing list, as a reply to your “save the date” email from January. And also a CC in the public programming committee list.

**Comment by prushforth** [comment]
Yes I will. Thanks.

**Comment by AmeliaBR** [comment]
I think we've covered all the necessary updates & this issue can be closed.
