### ISSUE TITLE
Video-conferencing and video hosting tools

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML-Workshop-2020#39]
For the new online format, we expect to have a few different types of video sessions:

- pre-recorded presentations, which would then be compiled by a moderator with introductions and extra information, and would be posted for participants

- panel discussions where different presenters and a moderator are talking live, and maybe participants could watch live and submit questions using a commenting system, but which would also be recorded and posted for participants to watch later

- scheduled live video chats for breakout or hack sessions, which may or may not be recorded

All the recorded videos should support captioning.  Live video chats could be paired with minuting in another app.

I can't see us having more than a dozen people talking in a panel session, but we might get more than that in a breakout session where we want it to be open for all participants to talk live.

This issue is therefore for discussing suggestions for what tools / software can do all this. Related, is how to pay for it, e.g., which organizations have subscriptions that they could use to host the sessions?

**Comment by AmeliaBR** [comment]
Useful link: [Best video conferencing apps and software for accessibility](https://bighack.org/best-videoconferencing-apps-and-software-for-accessibility/). Includes information on auto-caption software if we can't afford live human captioning, or for breakout sessions.

**Comment by prushforth** [comment]
Here's a link to the (WebRTC) software service mentioned by Karen: https://www.ringcentral.com/sem/video-conferencing.html
