### ISSUE TITLE
Online discussion forum software

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML-Workshop-2020#40]
As part of the new online-only workshop format, we want people to be able to contribute to the discussion on their own time, from any time zone. The plan is therefore to use structured discussion forums, not just live chat, to make it easier to review and contribute.

In particular, we want something that supports:

- Separate discussion pages for each topic / issue.

- Ideally, a way to tag/group/organize the different topic pages.

- Registered participants list.

- The ability for participants to subscribe to updates on a particular topic, or be notified of direct replies.

- A way to post images, links, and code samples in the discussion, and maybe other embeds like video or working code in iframes. (It would be nice if we could have the presentation videos embedded on the same page as the discussion, but a link out to a separate video hosting platform would do.)

- Moderation tools, including the ability to censor/edit anything contrary to the code of conduct, and ideally including a way to highlight important contributions, and to collapse (or move to a separate discussion) any off-topic tangents.

- Ideally, a way to thread replies or indicate what comment you're replying to (e.g., link back & quote).

These structured discussions would be paired up with a live text-chat option, such as IRC, for use by the hack/breakout sessions or more generally to support ad-hoc direct communication between participants.  Of course, if it is possible to combine both types of discussion in the same tool, that might be helpful to keep organized.

This issue is for discussion tool choices. Please also suggest any additions to the list of criteria above.

**Comment by AmeliaBR** [comment]
From today's program committee discussion, we're leaning to using the WICG discourse instance. There is already a web-mapping category: https://discourse.wicg.io/c/web-mapping/22

We'll need to check in with the moderators to make sure they're OK with us using it in this way. But benefits are:

- it's already set up, and will be maintained after the workshop is over
- sign up is fairly easy, although we wouldn't be able to limit discussion to registered participants
- the discussion would be visible to lots of other participant, hopefully prompting more engagement

**Comment by akuckartz** [comment]
A different tool: https://www.semantic-mediawiki.org/

**Comment by frastlin** [comment]
I attended another conference where Slack was used, and it pretty much has all those features.
The problem with using the existing forum, is that I'm not sure it's very good for live Q&A, and there could also be quite a few new topics that are not the current presentation. If we get the ability to make a thread Sticky, then that is what should happen with the official conference threads.

**Comment by prushforth** [comment]
I created a [gitter chat room](https://gitter.im/Maps4HTML/W3C-OGC-Workshop-Maps-For-Web) for this workshop, although I was going to send the link a bit closer to the date (so as to avoid having to moderate spam before the workshop).  We plan to use the WICG forum for topic-specific discussion, which can be very asynchronous and could possibly involve Web platform contributors as well.

**Comment by prushforth** [comment]
I remembered that we discussed something about irc integration with gitter, for those users who are familiar with the former but not the latter, so just bringing this to the attention of @tguild to see if anything can be done there. https://gitlab.com/gitlab-org/gitter/irc-bridge/-/wikis/Client-configuration

**Comment by tguild** [comment]
@shepazu was going to look into that. It seems there is an irc bridge already to gitter.

https://gitlab.com/gitlab-org/gitter/irc-bridge/-/blob/develop/README.md
