### ISSUE TITLE
Scope in web site

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-Workshop-2020#42]
Given the good discussion and refinement of the email [announcement](https://docs.google.com/document/d/1c3cICjSqh1KVaLTYoQf-47pORBrpWVbMiu09Zi9-FR4/edit) of the workshop at yesterday's meeting, could we update the web site to reflect the following statement, under [scope](https://www.w3.org/2020/maps/#scope):

"The scope of the workshop series is the standardization of dynamic, interactive maps as a first-class native component in the browser", maybe as the introductory sentence to [scope](https://www.w3.org/2020/maps/#scope)?

So, instead of reading as follows: 

> The workshop series is specifically about geographic map content displayed to end users — usually in an explorable, interactive viewer — within the context of websites and other applications built using the Web platform.

the first sentence would read:

> The workshop series is specifically about the standardization of dynamic, interactive maps as a first-class native component in the browser — an explorable, interactive viewer — within the context of websites and other applications built using the Web platform.

If acceptable, I can frame as a pull request.

**Comment by AmeliaBR** [comment]
I don't mind the change, if others are OK with the narrower scope.

Quibbling on wording: probably don't need to repeat the word “interactive” and “in the browser"/“in the context of websites” is likewise redundant. Maybe just:

> The workshop series is specifically about the standardization of dynamic, interactive maps as a first-class native component in the browser or other applications built using the Web platform.

**Comment by prushforth** [comment]
I will leave it as a pull request to merge before cfp opening, and if @sideshowbarker @tguild @shepazu @royrathbun @ghobona want, they can weigh in.
