### ISSUE TITLE
Workshop Agenda — top-level themes

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML-Workshop-2020#50]
Although we can't finalize an agenda until we have proposals from people who want to present, a little more detail on the [agenda page](https://www.w3.org/2020/maps/agenda) might be helpful.

We are currently planning that “Presentations will be grouped into themes, with one theme posted online per day”. And we already have some themes that we know we want to discuss.

Therefore, one thing we can decide at this point on a (tentative) schedule of themes & days.

Here's the rough list of themes I came up with, based on the [potential topics list](https://www.w3.org/2020/maps/#topics) already on the website, starting from some introductory themes & going into specifics:

1. The current state of web maps — e.g., common features, limitations, interoperability of existing frameworks / data servers

2. Extending the web platform for native map support — limitations and potential for changing HTML and other built-in browser features

3. Best practices for accessible map viewers

4. Optimizing map data formats (tiles, vectors, 3D) for web use — e.g., minimizing data transfer, supporting progressive rendering, integrating HTML annotations for features

5. Rendering and Performance of interactive map viewers in browsers

6. Client-side APIs for dynamic web mapping applications — what are web app authors trying to do & how can web standards support it?

7. World Wide maps — what are the requirements & difficulties with internationalization and localization of map data and viewer UI

8. Protecting user privacy, while supporting advanced map features

9. Hypermapping & security — supporting interconnected map data and mash-ups within cross-origin web security constraints

Please offer suggestions for other themes, modifications to these, or changes in the theme order. We'll settle on a list at the next programming committee telecon (Thursday May 28).

**Comment by AmeliaBR** [comment]
From today's discussion:

Amelia: Point 2 could be split, one session on extending the web platform in an open-ended way, one session about introducing specific proposals like MapML.

Gobe: It's strange to have a session on client-side APIs and not one on server APIs. We definitely need a discussion for people working on Open API, RESTful patterns, and so on. Also cloud computing / distributed services. Point 4 could be expanded to include web APIs.

Peter: I'm not sure people will understand “hypermapping”. Just call it security & then describe what you mean.

**Comment by prushforth** [comment]
I will quote Satoru Takagi's email a suggestion for a theme or category:  

> Decentralized Web Mapping design and concept.  

I had forgotten that decentralized Web mapping was an important concept in development of SVGMap, and indeed this is one of the motivations for the creation of the community group itself.
