### ISSUE TITLE
Github Security Alert (Jekyll dependency)

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML-Workshop-2020#52]
Opening this issue as a reminder to update the Jekyll dependencies in a day or two, after the patch has made it's way through the dependency tree.

See the alert: https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/network/alert/Gemfile.lock/activesupport/open 

I opened an issue on the Jekyll repo: https://github.com/jekyll/jekyll/issues/8210

**Comment by prushforth** [comment]
there seem to be quite a few of these piling up. I hope it doesn't put the web site at risk?

**Comment by AmeliaBR** [comment]
The Jekyll issue was cleared up, so I'll close this. There's another [active warning](https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/security/dependabot/Gemfile.lock/nokogiri/open), but it doesn't affect anything that we're doing.

Which is probably true about Jekyll as well. Because we're using these at the build step, and not doing anything too complicated with networking, it's fairly low probability that an issue will be serious. But still need to check.
