### ISSUE TITLE
Hide out-of-date info on CFP

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML-Workshop-2020#58]
Now that the deadline for the talk/session proposals is passed, that info is less relevant, and may actually distract from the call to register & the call for positions statements, which _are_ still open.

But, I don't want to just delete this info, since it's relevant that we had an open call & people may want to review the requirements.

My suggestion: in the relevant sections of the CFP (e.g., [“How can I suggest a presentation or panel session?”](https://www.w3.org/2020/maps/call-for-participation#talk-proposals)):

- add one line note “The deadline for submitting proposals for presentations has passed.”
- collapse the rest of the section (using details/summary), where the summary text is something like “Show submission requirements…”

Other text on the website (e.g., in the “Register Now” sidebar box) also needs to be cleaned up to focus on currently possible actions.

@nchan0154 said she'd take a pass at these, but if anyone spots anything else that needs updating, let her know here.

**Comment by nchan0154** [comment]
I've addressed the two areas you've pointed out in the WIP pull request and give it a more thorough once-over tomorrow. Has the hack/demo project deadline passed @AmeliaBR?

**Comment by AmeliaBR** [comment]
> Has the hack/demo project deadline passed

Yes, probably collapse that, too, same as talks.

**Comment by Malvoz** [comment]
I believe this was fixed in #61, can you close this? Thanks. :)
