### ISSUE TITLE
Panel - Stakeholders: Open source for Web Mapping

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-Workshop-2020#76]

**Comment by dmorissette** [comment]
I guess the obvious one for topic #1 could be an introduction round: "Please introduce yourself and your relationship with the open source web mapping ecosystem"

**Comment by prushforth** [comment]
Thanks Daniel.

One statement I saw on twitter from a well known web mapper was "Never in
1M years will WHATWG allow the integration of maps into HTML, for the
simple reason that the majority of them now run their own spatial data
infrastructure." What would the open source panel say to addressing this?

Peter

**Comment by prushforth** [comment]
References provided by @zcorpan during our call: 

[WHATWG working mode](https://whatwg.org/working-mode#additions)
[Launching new features in Chromium](https://www.chromium.org/blink/launching-features)
